---
- name: install python setup tools
  yum: name=python-setuptools    state=installed
  tags: supervisor

- name: install supervisor with easy_install
  shell: easy_install supervisor
  tags: supervisor

- name: configure supervisord
  shell: /usr/bin/echo_supervisord_conf > {{supervisor.config.file | default('/etc/supervisord.conf')}}
  tags: supervisor

- name: backup default configuration
  shell: cp {{supervisor.config.file | default('/etc/supervisord.conf')}} /etc/default.supervisord.conf creates=/etc/default.supervisord.conf
  tags: supervisor

- name: create log directory
  file: path={{supervisor.log.dir | default('/var/log/supervisord')}} state=directory recurse=yes
  tags: supervisor

- name: create relative configurations dir
  file: path={{supervisor.config.dir | default('/etc/supervisord.d')}} state=directory recurse=yes
  tags: supervisor

- name: tell supervisor to include relative configurations directory
  ini_file: dest={{supervisor.config.file | default('/etc/supervisord.conf')}}
            section=include
            option=files
            value={{supervisor.config.dir | default('/etc/supervisord.d')}}/*.ini
            state=present
  tags: supervisor

- name: configure web ui status checking server
  ini_file: dest={{supervisor.config.dir | default('/etc/supervisord.d')}}/{{supervisor.status.file | default('/etc/supervisord.conf')}}
            section=inet_http_server
            option={{item.key}}
            value={{item.value}}
            state=present
  with_dict: supervisor.status
  tags: supervisor

- name: add programs
  ini_file: dest={{supervisor.config.dir | default('/etc/supervisord.d')}}/{{item.0.file}}
            section="program:{{item.0.name}}"
            option={{item.1.split('=')[0]}}
            value={{item.1.split('=')[1]}}
            state=present
  with_subelements:
      - supervisor.programs
      - values
  tags: supervisor
