---
- name: install python setup tools
  yum: name=python-setuptools    state=installed
  tags: supervisor

- name: install supervisor with easy_install
  shell: easy_install supervisor
  tags: supervisor

- name: configure supervisord
  shell: /usr/bin/echo_supervisord_conf > {{supervisord.config.file}}
  tags: supervisor

- name: backup default configuration
  shell: cp {{supervisord.config.file}} {{supervisord.config.default}} creates={{supervisord.config.default}}
  tags: supervisor

- name: prepare necessary directories
  file: path={{item}} state=directory recurse=yes
  with_items:
    - "{{supervisord.log.dir}}"
    - "{{supervisord.config.dir}}"
    - "{{supervisord.runtime.dir}}"
  tags: supervisor

- name: configure runtime and log
  ini_file: dest={{supervisord.config.file}}
            section={{item.section}}
            option={{item.option}}
            value={{item.value}}
  with_items:
      - { section: unix_http_server, option: file, value: "{{supervisord.runtime.dir}}/{{supervisord.runtime.socket}}" }
      - { section: supervisorctl, option: serverurl, value: "unix://{{supervisord.runtime.dir}}/{{supervisord.runtime.socket}}" }
      - { section: supervisord, option: pidfile, value: "{{supervisord.runtime.dir}}/{{supervisord.runtime.pidfile}}" }
      - { section: supervisord, option: nodaemon, value: "{{supervisord.runtime.nodaemon}}" }
      - { section: supervisord, option: logfile, value: "{{supervisord.log.dir}}/{{supervisord.log.file}}" }
      - { section: supervisord, option: loglevel, value: "{{supervisord.log.level}}" }
  tags: supervisor

- name: tell supervisor to include relative configurations directory
  ini_file: dest={{supervisord.config.file}}
            section=include
            option=files
            value={{supervisord.config.dir}}/*.ini
            state=present
  tags: supervisor

- name: configure web ui status checking server
  ini_file: dest={{supervisord.config.dir}}/{{supervisord.http.file}}
            section=inet_http_server
            option={{item.key}}
            value={{item.value}}
            state=present
  with_dict: supervisord.http
  tags: supervisor

- name: add programs
  ini_file: dest={{supervisord.config.dir}}/{{item.0.file}}
            section="program:{{item.0.name}}"
            option={{item.1.split('=')[0]}}
            value={{item.1.split('=')[1]}}
            state=present
  with_subelements:
      - supervisor.programs
      - values
  when: supervisor.programs is defined
  tags: supervisor

- name: make sure supervisord is running and up-to-date
  shell: echo Magic...
  notify:
    - run supervisord
    - reread supervisord config
    - add programs to process group
    - change supervisord programs states
  tags: supervisor
